version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosqdata:/mosquitto/data

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MQTT_URL=mqtt://mosquitto:1883
      - MONGO_URL=mongodb://mongo:27017/iot_iiot
      - PLANT_ID=A1
      - JWT_SECRET=your-super-secret-production-jwt-key-change-this
      - FRONTEND_URL=http://localhost:8080
    depends_on:
      - mosquitto
      - mongo

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND=http://localhost:3000
    ports:
      - "8080:80"
    depends_on:
      - backend

  simulator:
    build: 
      context: ./simulator
      dockerfile: Dockerfile
    environment:
      - MQTT_URL=mqtt://mosquitto:1883
      - PLANT_ID=A1
    depends_on:
      - mosquitto
    command: "npm start"

volumes:
  mosqdata:
  mongodata: